[package]
name = "training_code"
version = "0.1.0"
authors = ["zhizhi.liu <zhizhi.liu@qunar.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version= "1", features=["derive"]}
serde_json = "1" 
tokio = {version= "1", features=["sync"]}